CC_SegundaAsignacion_v2/CRUD_3CAPAS_CORE6/WebMVC6/Models/ErrorViewModel.cs
namespace WebMVC6.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CC_SegundaAsignacion_v2/CRUD_3CAPAS_CORE6/WebMVC6/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebMVC6.Models;

namespace WebMVC6.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CC_SegundaAsignacion_v2/CRUD_3CAPAS_CORE6/WebMVC6/Controllers/IngenieroController.cs
using Microsoft.AspNetCore.Mvc;
using modelEntity;
using modelNeg;

namespace WebMVC6.Controllers
{
    public class IngenieroController : Controller
    {
        private IngenieroNeg objIngenieroNeg;
        public IngenieroController()
        {
            objIngenieroNeg = new IngenieroNeg();
        }
        // GET: Ingeniero
        public ActionResult Inicio()
        {
            List<Ingeniero> lista = objIngenieroNeg.findAll();
            return View(lista);
        }

        [HttpGet]
        public ActionResult Create()
        {
            mensajeInicio();
            return View();
        }
        [HttpPost]
        public ActionResult Create(Ingeniero objIngeniero)
        {
            mensajeInicio();
            objIngenieroNeg.create(objIngeniero);
            mensajeErrorRegistro(objIngeniero);
            return View();
        }
        public void mensajeInicio()
        {
            ViewBag.mensajeInicio = "Formulario de Registro de Ingenieros";
        }
        public void mensajeInicioUpdate()
        {
            ViewBag.mensajeInicio = "Formulario para actualizar ingeniero";
        }
        public void mensajeInicioDelete()
        {
            ViewBag.mensajeInicio = "¿Eliminar este registro de ingeniero?";
        }

        public void mensajeErrorRegistro(Ingeniero objIngeniero)
        {
            switch (objIngeniero.Estado)
            {
                case 10:
                    ViewBag.mensajeError = "";
                    break;

                case 1:
                    ViewBag.mensajeError = "";
                    break;

                case 100:
                    ViewBag.mensajeError = "solo se permiten numeros";
                    break;

                case 20:
                    ViewBag.mensajeError = "Campo Nombre Esta Vacio";
                    break;

                case 2:
                    ViewBag.mensajeError = "Excedio la longitud de la cadena en el campo nombre,solo se permiten 50 caracteres";
                    break;

                case 30:
                    ViewBag.mensajeError = "Campo Edad Esta Vacio";
                    break;

                case 3:
                    ViewBag.mensajeError = "Ingrese una edad valida";
                    break;

                case 40:
                    ViewBag.mensajeError = "Campo fecha nacimiento Esta Vacio";
                    break;

                case 4:
                    ViewBag.mensajeError = "Excedio la longitud de la cadena en el campo fecha nacimiento";
                    break;

                case 5:
                    ViewBag.mensajeError = "Ingeniero [" + objIngeniero.Id + "]ya esta registrado";
                    break;
                case 25:
                    ViewBag.mensajeError = "Error al eliminar el registro";
                    break;
                case 69:
                    ViewBag.mensajeError = "Error al actualizar registro";
                    break;

                case 99:
                    ViewBag.mensajeExito = "El Ingeniero fue registrado con éxito";
                    break;

                case 45:
                    ViewBag.mensajeExito = "Se ha eliminado el registro con éxito";
                    break;
                case 68:
                    ViewBag.mensajeExito = "Se ha actualizado el registro con éxito";
                    break;





            }
        }

        public ActionResult Find(string codigo)
        {
            Ingeniero objIngeniero = new Ingeniero(Convert.ToInt32(codigo));
            objIngenieroNeg.find(objIngeniero);
            return View(objIngeniero);
        }

        [HttpGet]
        public ActionResult Update(string id)
        {
            mensajeInicioUpdate();
            Ingeniero objIngeniero = new Ingeniero(Convert.ToInt32(id));
            objIngenieroNeg.find(objIngeniero);
            return View(objIngeniero);
        }
        [HttpPost]
        public ActionResult Update(Ingeniero objIngeniero)
        {
            mensajeInicioUpdate();  
            objIngenieroNeg.update(objIngeniero);
            mensajeErrorRegistro(objIngeniero);
            return View();
        }
        
        public ActionResult Delete()
        {
            mensajeInicioDelete();
            return View();
        }

        [HttpPost]
        public ActionResult Delete(Ingeniero objIngeniero)
        {
            mensajeInicioDelete();
            objIngenieroNeg.delete(objIngeniero);
            mensajeErrorRegistro(objIngeniero);
            return View();
        }
    }
}

CC_SegundaAsignacion_v2/CRUD_3CAPAS_CORE6/WebMVC6/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CC_SegundaAsignacion_v2/CRUD_3CAPAS_CORE6/WebMVC6/Views/Ingeniero/Create.cshtml
@model modelEntity.Ingeniero
@{
    ViewBag.Title = "Create";
}
<br /><br /><br />
<div class="container text-center text-light rounded bg-primary p-3 mb-5">
    <h1>
        @ViewBag.mensajeInicio
    </h1>
   
</div>
@using (Html.BeginForm())
{
    <div class="form-horizontal">

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_nac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Fecha_nac, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Altura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Altura, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <br>
        <div class="form-actions col-md-offset-2">
            <input class="btn btn-primary me-2" type="submit" name="btnguardar" value="Guardar" />
            @Html.ActionLink("Regresar al Listado", "Inicio")
        </div>
    

    </div>    

}
<div class="container text-center text-danger">
    <h1>
@ViewBag.mensajeError
    </h1>
    
</div>
<div class="container text-center text-success">
    <h1>
@ViewBag.mensajeExito
    </h1>
    
</div>

CC_SegundaAsignacion_v2/CRUD_3CAPAS_CORE6/WebMVC6/Views/Ingeniero/Delete.cshtml
@model List<modelEntity.Ingeniero>
@{
    ViewBag.Title = "Delete";
}
<br />
<br />
<br />
<hr>
<div class="container text-center text-light rounded bg-danger p-3 mb-5">
    <h1>
        @ViewBag.mensajeInicio
    </h1>
</div>
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <div class="form-actions col-md-offset-2 text-center">
            <input class="btn btn-danger me-5 btn-lg" type="submit" name="btneliminar" value="Eliminar" />|
            @Html.ActionLink("Regresar al Listado", "Inicio")
        </div>
    </div>

}
<div class="container text-center text-danger">
    <h1>
        @ViewBag.mensajeError
    </h1>

</div>
<div class="container text-center text-success">
    <h1>
        @ViewBag.mensajeExito
    </h1>

</div>

CC_SegundaAsignacion_v2/CRUD_3CAPAS_CORE6/WebMVC6/Views/Ingeniero/Edit.cshtml
@model modelEntity.Ingeniero

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Ingeniero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha_nac" class="control-label"></label>
                <input asp-for="Fecha_nac" class="form-control" />
                <span asp-validation-for="Fecha_nac" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Altura" class="control-label"></label>
                <input asp-for="Altura" class="form-control" />
                <span asp-validation-for="Altura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Inicio">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CC_SegundaAsignacion_v2/CRUD_3CAPAS_CORE6/WebMVC6/Views/Ingeniero/Find.cshtml
@model modelEntity.Ingeniero
@{
    ViewBag.Title = "Find";
}

<h1>Detalles Ingeniero</h1>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_nac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Fecha_nac, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Altura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Altura, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>


    </div>

}

CC_SegundaAsignacion_v2/CRUD_3CAPAS_CORE6/WebMVC6/Views/Ingeniero/Inicio.cshtml
@model List<modelEntity.Ingeniero>
@{
    ViewBag.Title = "Inicio";
}
<br />
<br />
<br />
<div class="container-fluid">
    <div>
        <a class="btn btn-primary" href="~/Ingeniero/create">Nuevo</a>
    </div>
    <hr />
    <table class="table">
        <tr class="btn-primary">
            <th>Codigo</th>
            <th>Nombre</th>
            <th>Edad</th>
            <th>FechaNac</th>
            <th>Altura</th>
            <th colspan="2">Operaciones</th>
        </tr>
        @foreach (var objIngeniero in Model)
        {
            <tr>
                <td>@objIngeniero.Id</td>
                <td>@objIngeniero.Nombre</td>
                <td>@objIngeniero.Edad</td>
                <td>@objIngeniero.Fecha_nac</td>
                <td>@objIngeniero.Altura</td>
                <!-- <td><a class="btn btn-success" href="~/Ingeniero/find/@objIngeniero.Id">Ver</a></td> -->
                <td><a class="btn btn-success" href="~/Ingeniero/update/@objIngeniero.Id">Actualizar</a></td>
                <td><a class="btn btn-danger" href="~/Ingeniero/delete/@objIngeniero.Id">Eliminar</a></td>
            </tr>
        }

    </table>
</div>

CC_SegundaAsignacion_v2/CRUD_3CAPAS_CORE6/WebMVC6/Views/Ingeniero/Update.cshtml
@model modelEntity.Ingeniero
@{
    ViewBag.Title = "Update";
}
<br />
<br />
<br />
<div class="container text-center text-light rounded bg-success p-3 mb-5">
    <h1>
        @ViewBag.mensajeInicio
    </h1>

</div>
@using (Html.BeginForm())
{
    <div class="form-horizontal mt-3">

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_nac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Fecha_nac, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Altura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Altura, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <br>
        <div class="form-actions col-md-offset-2">
            <input class="btn btn-success me-2" type="submit" name="btnguardar" value="Guardar" />
            @Html.ActionLink("Regresar al Listado", "Inicio")
        </div>


    </div>

}
<div class="container text-center text-danger">
    <h1>
        @ViewBag.mensajeError
    </h1>

</div>
<div class="container text-center text-success">
    <h1>
        @ViewBag.mensajeExito
    </h1>

</div>

CC_SegundaAsignacion_v2/CRUD_3CAPAS_CORE6/WebMVC6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMVC6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebMVC6.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebMVC6</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ingeniero" asp-action="Inicio">Ingeniero</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebMVC6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>